language: java
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean frontend:build backend:shadowJar

notifications:
  email:
    on_failure: always
    on_success: never
